version: '2'
services:
    web:
        build: .
        ports: 
            - 8080:8080
        env_file: .rabbitmq.env
        entrypoint: python wsgi.py
    
    worker:
        build: .
        env_file: .rabbitmq.env
        entrypoint: celery worker -A tasks -P gevent --loglevel=info
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    rabbitmq:
        image: rabbitmq:latest
        env_file: .rabbitmq.env

    postgres:
        image: postgres:latest
        env_file: .postgres.env

    registry:
        image: registry:latest
