version: '2'
services:
    web:
        build: .
        ports: 
            - 8080:8080
        volumes:
            - ./static:/usr/src/app/static
        env_file: .rabbitmq.env
        entrypoint: python wsgi.py
    
    worker:
        build: .
        env_file: .rabbitmq.env
        entrypoint: celery worker -A tasks -P gevent -c 1000 --loglevel=info
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        tmpfs: /tmp
 
    rabbitmq:
        image: rabbitmq:latest
        env_file: .rabbitmq.env

    postgres:
        image: postgres:latest
        env_file: .postgres.env
        volumes:
            - pgdata:/var/lib/postgresql/data

    registry:
        image: registry:2
        ports:
            - 5000:5000
        volumes:
           - registry:/var/lib/registry

volumes:
    pgdata:
    registry:
