version: '2'
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:latest
		env_file: .rabbitmq.env

    database:
        hostname: postgres
        image: postgres:latest
		env_file: .postgres.env

    registry:
        hostname: registry
        image: registry:latest
